### PR TITLE
API-ification

### PR DESCRIPTION
**Pull request by tleeuwenburg**
I did this so that I could use this in an API call as easily as from the command-line. I thought I'd share the work.

### CODE REVIEW

**Comment by tleeuwenburg** [comment]
After creating the initial request, I've gone back and added Python 2/3 compatibility. I wanted to use Python 3, but didn't want to break compatibility either.

**Comment by danieldiekmeier** [comment]
Thank you, that's really great. (And unexpected!) Could you also add usage information to the README.md?

**Comment by tleeuwenburg** [comment]
I just committed some basic documentation. I hope that's the kind of thing you had in mind. I think the module is simple enough people can just read the code if the need more details...?

**Comment by danieldiekmeier** [comment]
Yes, that's great, thank you. I just wanted to make it obvious that it can be used as a module.

**Pull request merged**
